# Generated by Django 4.1.6 on 2023-02-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=255)),
                ('name_place', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст отзыва', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тура')),
                ('description', models.TextField(verbose_name='Описание тура')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображения')),
                ('slug', models.SlugField(unique=True)),
                ('date_published', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('date_departure', models.DateTimeField(verbose_name='Дата и время выезда')),
                ('date_arrival', models.DateTimeField(verbose_name='Дата и время приезда')),
                ('quantity_limit', models.PositiveIntegerField(null=True)),
                ('actual_limit', models.IntegerField(default=30, editable=False, null=True)),
                ('is_hot', models.BooleanField(blank=True, null=True, verbose_name='Горячий тур')),
                ('complexity', models.CharField(choices=[('e', 'Легкий'), ('m', 'Средний'), ('h', 'Сложный'), ('s-h', 'Экстра-сложный')], default='', max_length=255, verbose_name='Сложность')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.category', verbose_name='Категория')),
                ('from_where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_where', to='tour.place', verbose_name='Откуда')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='tour.place', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
