# Generated by Django 4.1.6 on 2023-02-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Изображения'),
        ),
    ]
