# Generated by Django 4.1.7 on 2023-02-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_images_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображения'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
